// src/renderer/components/CharacterPanel.vue
<template>
  <el-aside :style="{ width: isCollapsed ? '50px' : '320px', borderLeft: '1px solid #e0e0e0', display: 'flex', flexDirection: 'column' }">
    <div :style="{ padding: isCollapsed ? '12px 8px' : '12px', borderBottom: '1px solid #e0e0e0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }">
      <span v-if="!isCollapsed" style="font-size: 16px; font-weight: 500">人物</span>
      <div :style="{ display: 'flex', gap: '4px', margin: isCollapsed ? '0 auto' : '' }">
        <el-button v-if="!isCollapsed" :icon="Plus" circle size="small" @click="handleOpenCreateDialog" />
        <el-button :icon="isCollapsed ? ArrowRight : ArrowLeft" circle size="small" @click="toggleCollapse" />
      </div>
    </div>

    <div v-if="!isCollapsed && selectedCharacters.size > 0" style="padding: 8px; background-color: #ecf5ff">
      <span style="font-size: 12px">已选择 {{ selectedCharacters.size }} 个人物</span>
    </div>

    <el-scrollbar v-if="!isCollapsed" style="flex: 1">
      <div style="padding: 8px">
        <div
          v-for="character in characters"
          :key="character.id"
          class="character-item"
          @click="toggleCharacterSelection(character.id)"
        >
          <el-checkbox
            :model-value="selectedCharacters.has(character.id)"
            @change="toggleCharacterSelection(character.id)"
            style="margin-right: 12px"
          />
          <el-avatar :size="32" style="background-color: #67c23a; margin-right: 12px">
            <el-icon><User /></el-icon>
          </el-avatar>
          <div style="flex: 1; min-width: 0">
            <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 4px">
              <span style="font-size: 14px; font-weight: 500">{{ character.name }}</span>
              <el-tag v-if="selectedCharacters.has(character.id)" size="small" type="primary">已选中</el-tag>
            </div>
            <div v-if="character.personality" style="font-size: 12px; color: #666; white-space: nowrap; overflow: hidden; text-overflow: ellipsis">
              {{ character.personality }}
            </div>
          </div>
          <div class="character-actions">
            <el-button :icon="Edit" circle size="small" text @click.stop="handleOpenEditDialog(character)" />
            <el-button :icon="Delete" circle size="small" text @click.stop="deleteCharacter(character.id)" />
          </div>
        </div>
        <el-empty v-if="characters.length === 0" description="暂无人物，点击右上角添加" :image-size="60" />
      </div>
    </el-scrollbar>

    <el-dialog
      v-model="dialogOpen"
      :title="editMode ? '编辑人物' : '添加人物'"
      width="500px"
    >
      <el-form label-width="80px">
        <el-form-item label="姓名">
          <el-input v-model="name" placeholder="请输入姓名" />
        </el-form-item>
        <el-form-item label="性格">
          <el-input
            v-model="personality"
            type="textarea"
            :rows="2"
            placeholder="请输入性格描述"
          />
        </el-form-item>
        <el-form-item label="背景">
          <el-input
            v-model="background"
            type="textarea"
            :rows="3"
            placeholder="请输入背景故事"
          />
        </el-form-item>
        <el-form-item label="关系">
          <el-input
            v-model="relationships"
            type="textarea"
            :rows="3"
            placeholder='{"张三": "朋友", "李四": "同事"}'
          />
          <template #footer>
            <span style="font-size: 12px; color: #999">例如: {"张三": "朋友", "李四": "同事"}</span>
          </template>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="handleCloseDialog">取消</el-button>
        <el-button type="primary" :disabled="!name.trim()" @click="handleSubmit">
          {{ editMode ? '保存' : '创建' }}
        </el-button>
      </template>
    </el-dialog>
  </el-aside>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { storeToRefs } from 'pinia';
import { Plus, Edit, Delete, User, ArrowLeft, ArrowRight } from '@element-plus/icons-vue';
import { useCharacterStore } from '../stores/characterStore';

const characterStore = useCharacterStore();
const { characters, selectedCharacters } = storeToRefs(characterStore);
const { createCharacter, updateCharacter, deleteCharacter, toggleCharacterSelection } = characterStore;

const dialogOpen = ref(false);
const editMode = ref(false);
const editId = ref<string | null>(null);
const name = ref('');
const personality = ref('');
const background = ref('');
const relationships = ref('');
const isCollapsed = ref(false);

const toggleCollapse = () => {
  isCollapsed.value = !isCollapsed.value;
};

const handleOpenCreateDialog = () => {
  editMode.value = false;
  name.value = '';
  personality.value = '';
  background.value = '';
  relationships.value = '';
  dialogOpen.value = true;
};

const handleOpenEditDialog = (character: any) => {
  editMode.value = true;
  editId.value = character.id;
  name.value = character.name;
  personality.value = character.personality || '';
  background.value = character.background || '';
  relationships.value = character.relationships || '';
  dialogOpen.value = true;
};

const handleCloseDialog = () => {
  dialogOpen.value = false;
  name.value = '';
  personality.value = '';
  background.value = '';
  relationships.value = '';
};

const handleSubmit = async () => {
  if (!name.value.trim()) return;

  try {
    const characterData = {
      name: name.value,
      personality: personality.value,
      background: background.value,
      relationships: relationships.value,
      avatar: '',
    };

    if (editMode.value && editId.value) {
      await updateCharacter(editId.value, characterData);
    } else {
      await createCharacter(characterData);
    }
    handleCloseDialog();
  } catch (error) {
    console.error('Failed to save character:', error);
  }
};
</script>

<style scoped>
.character-item {
  position: relative;
  display: flex;
  align-items: center;
  padding: 12px;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.2s;
}

.character-item:hover {
  background-color: #f5f5f5;
}

.character-item:hover .character-actions {
  opacity: 1;
}

.character-actions {
  position: absolute;
  top: 8px;
  right: 8px;
  opacity: 0;
  transition: opacity 0.2s;
}
</style>

// src/renderer/components/CharacterPanel.tsx
import React, { useState } from 'react';
import {
  Box,
  Typography,
  List,
  ListItem,
  ListItemText,
  IconButton,
  Avatar,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Checkbox,
  Chip,
} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';
import EditIcon from '@mui/icons-material/Edit';
import PersonIcon from '@mui/icons-material/Person';
import { useCharacterStore } from '../store/characterStore';

export default function CharacterPanel() {
  const { characters, selectedCharacters, createCharacter, updateCharacter, deleteCharacter, toggleCharacterSelection } = useCharacterStore();
  
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [editId, setEditId] = useState<string | null>(null);
  const [name, setName] = useState('');
  const [personality, setPersonality] = useState('');
  const [background, setBackground] = useState('');
  const [relationships, setRelationships] = useState('');

  const handleOpenCreateDialog = () => {
    setEditMode(false);
    setName('');
    setPersonality('');
    setBackground('');
    setRelationships('');
    setDialogOpen(true);
  };

  const handleOpenEditDialog = (character: any) => {
    setEditMode(true);
    setEditId(character.id);
    setName(character.name);
    setPersonality(character.personality || '');
    setBackground(character.background || '');
    setRelationships(character.relationships || '');
    setDialogOpen(true);
  };

  const handleCloseDialog = () => {
    setDialogOpen(false);
    setName('');
    setPersonality('');
    setBackground('');
    setRelationships('');
  };

  const handleSubmit = async () => {
    if (!name.trim()) return;

    try {
      const characterData = {
        name,
        personality,
        background,
        relationships,
      };

      if (editMode && editId) {
        await updateCharacter(editId, characterData);
      } else {
        await createCharacter(characterData);
      }
      handleCloseDialog();
    } catch (error) {
      console.error('Failed to save character:', error);
    }
  };

  return (
    <Box sx={{ width: 320, display: 'flex', flexDirection: 'column', borderLeft: 1, borderColor: 'divider' }}>
      <Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Typography variant="h6">人物</Typography>
        <IconButton size="small" onClick={handleOpenCreateDialog}>
          <AddIcon />
        </IconButton>
      </Box>

      {selectedCharacters.size > 0 && (
        <Box sx={{ p: 1, bgcolor: 'action.selected' }}>
          <Typography variant="caption" display="block" gutterBottom>
            已选择 {selectedCharacters.size} 个人物
          </Typography>
        </Box>
      )}

      <List sx={{ flex: 1, overflow: 'auto' }}>
        {characters.map((character) => (
          <ListItem
            key={character.id}
            button
            onClick={() => toggleCharacterSelection(character.id)}
            secondaryAction={
              <>
                <IconButton
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation();
                    handleOpenEditDialog(character);
                  }}
                >
                  <EditIcon fontSize="small" />
                </IconButton>
                <IconButton
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation();
                    deleteCharacter(character.id);
                  }}
                >
                  <DeleteIcon fontSize="small" />
                </IconButton>
              </>
            }
          >
            <Checkbox
              edge="start"
              checked={selectedCharacters.has(character.id)}
              sx={{ mr: 1 }}
            />
            <Avatar sx={{ mr: 2, bgcolor: 'secondary.main' }}>
              <PersonIcon />
            </Avatar>
            <ListItemText
              primary={
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  <Typography variant="subtitle2">{character.name}</Typography>
                  {selectedCharacters.has(character.id) && (
                    <Chip label="已选中" size="small" color="primary" variant="outlined" />
                  )}
                </Box>
              }
              secondary={
                <>
                  {character.personality && (
                    <Typography variant="caption" color="text.secondary" noWrap>
                      {character.personality}
                    </Typography>
                  )}
                </>
              }
            />
          </ListItem>
        ))}
        {characters.length === 0 && (
          <Box sx={{ p: 2, textAlign: 'center' }}>
            <Typography variant="body2" color="text.secondary">
              暂无人物，点击右上角添加
            </Typography>
          </Box>
        )}
      </List>

      <Dialog open={dialogOpen} onClose={handleCloseDialog} maxWidth="sm" fullWidth>
        <DialogTitle>{editMode ? '编辑人物' : '添加人物'}</DialogTitle>
        <DialogContent>
          <TextField
            autoFocus
            label="姓名"
            fullWidth
            value={name}
            onChange={(e) => setName(e.target.value)}
            sx={{ mt: 2, mb: 2 }}
          />
          <TextField
            label="性格"
            fullWidth
            multiline
            rows={2}
            value={personality}
            onChange={(e) => setPersonality(e.target.value)}
            sx={{ mb: 2 }}
          />
          <TextField
            label="背景"
            fullWidth
            multiline
            rows={3}
            value={background}
            onChange={(e) => setBackground(e.target.value)}
            sx={{ mb: 2 }}
          />
          <TextField
            label="关系 (JSON格式)"
            fullWidth
            multiline
            rows={3}
            value={relationships}
            onChange={(e) => setRelationships(e.target.value)}
            placeholder='{"张三": "朋友", "李四": "同事"}'
            helperText="例如: {&quot;张三&quot;: &quot;朋友&quot;, &quot;李四&quot;: &quot;同事&quot;}"
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseDialog}>取消</Button>
          <Button onClick={handleSubmit} variant="contained" disabled={!name.trim()}>
            {editMode ? '保存' : '创建'}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
