// src/renderer/components/CreateProjectDialog.vue
<template>
  <el-dialog
    v-model="visible"
    title="创建新项目"
    width="500px"
    @close="handleClose"
  >
    <el-form label-width="80px">
      <el-form-item label="项目标题">
        <el-input v-model="title" placeholder="请输入项目标题" />
      </el-form-item>
      <el-form-item label="项目描述">
        <el-input
          v-model="description"
          type="textarea"
          :rows="4"
          placeholder="请输入项目描述（可选）"
        />
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="handleClose">取消</el-button>
      <el-button type="primary" :disabled="!title.trim()" @click="handleSubmit">
        创建
      </el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useProjectStore } from '../stores/projectStore';

interface Props {
  modelValue: boolean;
}

interface Emits {
  (e: 'update:modelValue', value: boolean): void;
  (e: 'close'): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const projectStore = useProjectStore();
const { createProject } = projectStore;

const visible = ref(props.modelValue);
const title = ref('');
const description = ref('');

watch(
  () => props.modelValue,
  (val) => {
    visible.value = val;
  }
);

watch(
  visible,
  (val) => {
    emit('update:modelValue', val);
  }
);

const handleSubmit = async () => {
  if (!title.value.trim()) return;

  try {
    await createProject(title.value, description.value);
    title.value = '';
    description.value = '';
    visible.value = false;
  } catch (error) {
    console.error('Failed to create project:', error);
  }
};

const handleClose = () => {
  title.value = '';
  description.value = '';
  visible.value = false;
};
</script>

// src/renderer/components/CreateProjectDialog.tsx
import React, { useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Button,
  Box,
} from '@mui/material';
import { useProjectStore } from '../store/projectStore';

interface CreateProjectDialogProps {
  open: boolean;
  onClose: () => void;
}

export default function CreateProjectDialog({ open, onClose }: CreateProjectDialogProps) {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const { createProject } = useProjectStore();

  const handleSubmit = async () => {
    if (!title.trim()) return;

    try {
      await createProject(title, description);
      setTitle('');
      setDescription('');
      onClose();
    } catch (error) {
      console.error('Failed to create project:', error);
    }
  };

  const handleClose = () => {
    setTitle('');
    setDescription('');
    onClose();
  };

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
      <DialogTitle>创建新项目</DialogTitle>
      <DialogContent>
        <Box sx={{ pt: 1 }}>
          <TextField
            autoFocus
            label="项目标题"
            fullWidth
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            sx={{ mb: 2 }}
          />
          <TextField
            label="项目描述"
            fullWidth
            multiline
            rows={4}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
        </Box>
      </DialogContent>
      <DialogActions>
        <Button onClick={handleClose}>取消</Button>
        <Button onClick={handleSubmit} variant="contained" disabled={!title.trim()}>
          创建
        </Button>
      </DialogActions>
    </Dialog>
  );
}
