// src/renderer/components/MainLayout.vue
<template>
  <el-container style="height: 100vh; display: flex; flex-direction: column">
    <el-header style="background-color: #1976d2; color: white; padding: 0 16px; flex-shrink: 0; height: 60px">
      <el-row align="middle" style="height: 100%">
        <el-icon :size="24" style="margin-right: 12px">
          <HomeFilled />
        </el-icon>
        <span style="font-size: 18px; font-weight: 500; flex: 1">NovelAI Writer</span>
        <ProjectSelector style="margin: 0 8px" />
        <el-button
          :icon="Setting"
          circle
          style="margin-left: 8px"
          @click="showSettings = true"
        />
        <el-dropdown trigger="click" @command="handleMenuCommand">
          <el-button :icon="MoreFilled" circle />
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item command="createProject">新建项目</el-dropdown-item>
              <el-dropdown-item command="settings">LLM设置</el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
      </el-row>
    </el-header>

    <el-container style="flex: 1; overflow: hidden; display: flex; flex-direction: row">
      <TimelinePanel />
      <ChatPanel />
      <CharacterPanel />
    </el-container>

    <CreateProjectDialog
      v-model="showCreateProject"
      @close="showCreateProject = false"
    />
    
    <LLMSettingsDialog
      v-model="showSettings"
      @close="showSettings = false"
    />
  </el-container>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { HomeFilled, Setting, MoreFilled } from '@element-plus/icons-vue';
import { useProjectStore } from '../stores/projectStore';
import { useChatStore } from '../stores/chatStore';
import { useTimelineStore } from '../stores/timelineStore';
import { useCharacterStore } from '../stores/characterStore';
import TimelinePanel from './TimelinePanel.vue';
import ChatPanel from './ChatPanel.vue';
import CharacterPanel from './CharacterPanel.vue';
import ProjectSelector from './ProjectSelector.vue';
import CreateProjectDialog from './CreateProjectDialog.vue';
import LLMSettingsDialog from './LLMSettingsDialog.vue';

const projectStore = useProjectStore();
const chatStore = useChatStore();
const timelineStore = useTimelineStore();
const characterStore = useCharacterStore();

const showSettings = ref(false);
const showCreateProject = ref(false);

watch(
  () => projectStore.currentProject,
  async (currentProject) => {
    if (currentProject) {
      await chatStore.loadChats(currentProject.id);
      await timelineStore.loadNodes(currentProject.id);
      await characterStore.loadCharacters(currentProject.id);
    }
  },
  { immediate: true }
);

const handleMenuCommand = (command: string) => {
  if (command === 'createProject') {
    showCreateProject.value = true;
  } else if (command === 'settings') {
    showSettings.value = true;
  }
};
</script>

// src/renderer/components/MainLayout.tsx
import React, { useEffect } from 'react';
import { Box, AppBar, Toolbar, Typography, IconButton, Menu, MenuItem } from '@mui/material';
import HomeIcon from '@mui/icons-material/Home';
import SettingsIcon from '@mui/icons-material/Settings';
import { useProjectStore } from '../store/projectStore';
import { useChatStore } from '../store/chatStore';
import { useTimelineStore } from '../store/timelineStore';
import { useCharacterStore } from '../store/characterStore';
import ChatPanel from './ChatPanel';
import TimelinePanel from './TimelinePanel';
import CharacterPanel from './CharacterPanel';
import ProjectSelector from './ProjectSelector';
import CreateProjectDialog from './CreateProjectDialog';
import LLMSettingsDialog from './LLMSettingsDialog';

export default function MainLayout() {
  const { currentProject } = useProjectStore();
  const { loadChats } = useChatStore();
  const { loadNodes } = useTimelineStore();
  const { loadCharacters } = useCharacterStore();
  
  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
  const [showSettings, setShowSettings] = React.useState(false);
  const [showCreateProject, setShowCreateProject] = React.useState(false);

  const handleMenuClick = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const handleMenuClose = () => {
    setAnchorEl(null);
  };

  const handleSettingsOpen = () => {
    setShowSettings(true);
    handleMenuClose();
  };

  useEffect(() => {
    if (currentProject) {
      loadChats(currentProject.id);
      loadNodes(currentProject.id);
      loadCharacters(currentProject.id);
    }
  }, [currentProject, loadChats, loadNodes, loadCharacters]);

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
      <AppBar position="static" elevation={1}>
        <Toolbar variant="dense">
          <HomeIcon sx={{ mr: 2 }} />
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            NovelAI Writer
          </Typography>
          
          <ProjectSelector />
          
          <IconButton color="inherit" onClick={handleSettingsOpen}>
            <SettingsIcon />
          </IconButton>
          <IconButton color="inherit" onClick={handleMenuClick}>
            <SettingsIcon />
          </IconButton>
        </Toolbar>
      </AppBar>

      <Menu
        anchorEl={anchorEl}
        open={Boolean(anchorEl)}
        onClose={handleMenuClose}
      >
        <MenuItem onClick={() => setShowCreateProject(true)}>新建项目</MenuItem>
        <MenuItem onClick={handleSettingsOpen}>LLM设置</MenuItem>
      </Menu>

      <Box sx={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
        <TimelinePanel />
        <ChatPanel />
        <CharacterPanel />
      </Box>

      <CreateProjectDialog
        open={showCreateProject}
        onClose={() => setShowCreateProject(false)}
      />
      
      <LLMSettingsDialog
        open={showSettings}
        onClose={() => setShowSettings(false)}
      />
    </Box>
  );
}
