// src/renderer/components/ProjectSelector.vue
<template>
  <div v-if="projects.length > 0" style="min-width: 200px; margin-left: 8px">
    <el-select
      v-model="selectedProjectId"
      placeholder="选择项目"
      size="small"
      style="width: 100%"
    >
      <el-option
        v-for="project in projects"
        :key="project.id"
        :label="project.title"
        :value="project.id"
      />
    </el-select>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { storeToRefs } from 'pinia';
import { useProjectStore } from '../stores/projectStore';

const projectStore = useProjectStore();
const { projects, currentProject } = storeToRefs(projectStore);
const { selectProject } = projectStore;

const selectedProjectId = ref(currentProject.value?.id || '');

watch(
  () => selectedProjectId.value,
  (newId) => {
    selectProject(newId);
  }
);

watch(
  () => currentProject.value?.id,
  (newId) => {
    if (newId) {
      selectedProjectId.value = newId;
    }
  }
);
</script>

// src/renderer/components/ProjectSelector.tsx
import React from 'react';
import { Select, MenuItem, FormControl, InputLabel, Typography, Box } from '@mui/material';
import { useProjectStore } from '../store/projectStore';

export default function ProjectSelector() {
  const { projects, currentProject, selectProject } = useProjectStore();

  if (projects.length === 0) {
    return null;
  }

  return (
    <Box sx={{ minWidth: 200, ml: 2 }}>
      <FormControl size="small" fullWidth>
        <InputLabel>项目</InputLabel>
        <Select
          value={currentProject?.id || ''}
          label="项目"
          onChange={(e) => selectProject(e.target.value as string)}
        >
          {projects.map((project) => (
            <MenuItem key={project.id} value={project.id}>
              <Typography noWrap>{project.title}</Typography>
            </MenuItem>
          ))}
        </Select>
      </FormControl>
    </Box>
  );
}
