// src/renderer/components/TimelinePanel.vue
<template>
  <el-aside :style="{ width: isCollapsed ? '50px' : '300px', borderRight: '1px solid #e0e0e0', display: 'flex', flexDirection: 'column' }">
    <div :style="{ padding: isCollapsed ? '12px 8px' : '12px', borderBottom: '1px solid #e0e0e0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }">
      <span v-if="!isCollapsed" style="font-size: 16px; font-weight: 500">时间线</span>
      <div :style="{ display: 'flex', gap: '4px', margin: isCollapsed ? '0 auto' : '' }">
        <el-button v-if="!isCollapsed" :icon="Plus" circle size="small" @click="handleOpenCreateDialog" />
        <el-button :icon="isCollapsed ? ArrowLeft : ArrowRight" circle size="small" @click="toggleCollapse" />
      </div>
    </div>

    <el-scrollbar v-if="!isCollapsed" style="flex: 1">
      <div style="padding: 8px">
        <div
          v-for="node in nodes"
          :key="node.id"
          :class="['node-item', { 'node-selected': selectedNode?.id === node.id }]"
          @click="handleSelect(node.id)"
        >
          <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 4px">
            <el-icon v-if="selectedNode?.id === node.id" color="#409eff">
              <CircleCheck />
            </el-icon>
            <span style="font-size: 14px; font-weight: 500">{{ node.title }}</span>
          </div>
          <div style="font-size: 12px; color: #666; margin-bottom: 2px">
            {{ formatDate(node.date) }}
          </div>
           <div v-if="node.content" style="font-size: 12px; color: #999; white-space: nowrap; overflow: hidden; text-overflow: ellipsis">
            {{ node.content }}
          </div>
          <div class="node-actions">
            <el-button :icon="Edit" circle size="small" text @click.stop="handleOpenEditDialog(node)" />
            <el-button :icon="Delete" circle size="small" text @click.stop="deleteNode(node.id)" />
          </div>
        </div>
        <el-empty v-if="nodes.length === 0" description="暂无时间节点，点击右上角添加" :image-size="60" />
      </div>
    </el-scrollbar>

    <el-dialog
      v-model="dialogOpen"
      :title="editMode ? '编辑时间节点' : '添加时间节点'"
      width="500px"
    >
      <el-form label-width="80px">
        <el-form-item label="标题">
          <el-input v-model="title" placeholder="请输入标题" />
        </el-form-item>
        <el-form-item label="日期">
          <el-date-picker
            v-model="date"
            type="date"
            placeholder="选择日期"
            style="width: 100%"
            value-format="YYYY-MM-DD"
          />
        </el-form-item>
        <el-form-item label="描述">
          <el-input
            v-model="description"
            type="textarea"
            :rows="4"
            placeholder="请输入描述"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="handleCloseDialog">取消</el-button>
        <el-button type="primary" :disabled="!title.trim()" @click="handleSubmit">
          {{ editMode ? '保存' : '创建' }}
        </el-button>
      </template>
    </el-dialog>
  </el-aside>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { storeToRefs } from 'pinia';
import { Plus, Edit, Delete, CircleCheck, ArrowLeft, ArrowRight } from '@element-plus/icons-vue';
import { useTimelineStore } from '../stores/timelineStore';
import { formatDate } from '../../shared/utils';

const timelineStore = useTimelineStore();
const { nodes, selectedNode } = storeToRefs(timelineStore);
const { createNode, updateNode, deleteNode, selectNode } = timelineStore;

const dialogOpen = ref(false);
const editMode = ref(false);
const editId = ref<string | null>(null);
const title = ref('');
const date = ref('');
const description = ref('');
const isCollapsed = ref(false);

const toggleCollapse = () => {
  isCollapsed.value = !isCollapsed.value;
};

const handleOpenCreateDialog = () => {
  editMode.value = false;
  title.value = '';
  date.value = new Date().toISOString().split('T')[0];
  description.value = '';
  dialogOpen.value = true;
};

const handleOpenEditDialog = (node: any) => {
  editMode.value = true;
  editId.value = node.id;
  title.value = node.title;
  date.value = node.date || '';
  description.value = node.description || '';
  dialogOpen.value = true;
};

const handleCloseDialog = () => {
  dialogOpen.value = false;
  title.value = '';
  date.value = '';
  description.value = '';
};

const handleSubmit = async () => {
  if (!title.value.trim()) return;

  try {
    const content = `Date: ${date.value}\nDescription: ${description.value}`;
    if (editMode.value && editId.value) {
      await updateNode(editId.value, { title: title.value, content });
    } else {
      await createNode(title.value, content);
    }
    handleCloseDialog();
  } catch (error) {
    console.error('Failed to save timeline node:', error);
  }
};

const handleSelect = (id: string) => {
  if (selectedNode.value?.id === id) {
    selectNode(null);
  } else {
    selectNode(id);
  }
};
</script>

<style scoped>
.node-item {
  position: relative;
  padding: 12px;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.2s;
  border: 1px solid transparent;
}

.node-item:hover {
  background-color: #f5f5f5;
}

.node-item:hover .node-actions {
  opacity: 1;
}

.node-selected {
  background-color: #ecf5ff;
  border-color: #409eff;
}

.node-actions {
  position: absolute;
  top: 8px;
  right: 8px;
  opacity: 0;
  transition: opacity 0.2s;
}
</style>

// src/renderer/components/TimelinePanel.tsx
import React, { useState } from 'react';
import {
  Box,
  Typography,
  List,
  ListItem,
  ListItemText,
  IconButton,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Chip,
} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';
import EditIcon from '@mui/icons-material/Edit';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import { useTimelineStore } from '../store/timelineStore';
import { formatDate } from '../../shared/utils';

export default function TimelinePanel() {
  const { nodes, selectedNode, createNode, updateNode, deleteNode, selectNode } = useTimelineStore();
  
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [editId, setEditId] = useState<string | null>(null);
  const [title, setTitle] = useState('');
  const [date, setDate] = useState('');
  const [description, setDescription] = useState('');

  const handleOpenCreateDialog = () => {
    setEditMode(false);
    setTitle('');
    setDate(new Date().toISOString().split('T')[0]);
    setDescription('');
    setDialogOpen(true);
  };

  const handleOpenEditDialog = (node: any) => {
    setEditMode(true);
    setEditId(node.id);
    setTitle(node.title);
    setDate(node.date.split('T')[0]);
    setDescription(node.description);
    setDialogOpen(true);
  };

  const handleCloseDialog = () => {
    setDialogOpen(false);
    setTitle('');
    setDate('');
    setDescription('');
  };

  const handleSubmit = async () => {
    if (!title.trim()) return;

    try {
      if (editMode && editId) {
        await updateNode(editId, { title, date, description });
      } else {
        await createNode(title, date, description);
      }
      handleCloseDialog();
    } catch (error) {
      console.error('Failed to save timeline node:', error);
    }
  };

  const handleSelect = (id: string) => {
    if (selectedNode?.id === id) {
      selectNode(null);
    } else {
      selectNode(id);
    }
  };

  return (
    <Box sx={{ width: 300, display: 'flex', flexDirection: 'column', borderRight: 1, borderColor: 'divider' }}>
      <Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Typography variant="h6">时间线</Typography>
        <IconButton size="small" onClick={handleOpenCreateDialog}>
          <AddIcon />
        </IconButton>
      </Box>

      <List sx={{ flex: 1, overflow: 'auto' }}>
        {nodes.map((node) => (
          <ListItem
            key={node.id}
            button
            selected={selectedNode?.id === node.id}
            onClick={() => handleSelect(node.id)}
            secondaryAction={
              <>
                <IconButton
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation();
                    handleOpenEditDialog(node);
                  }}
                >
                  <EditIcon fontSize="small" />
                </IconButton>
                <IconButton
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation();
                    deleteNode(node.id);
                  }}
                >
                  <DeleteIcon fontSize="small" />
                </IconButton>
              </>
            }
          >
            <ListItemText
              primary={
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  {selectedNode?.id === node.id && <CheckCircleIcon color="primary" fontSize="small" />}
                  <Typography variant="subtitle2" noWrap>
                    {node.title}
                  </Typography>
                </Box>
              }
              secondary={
                <>
                  <Typography variant="caption" display="block">
                    {formatDate(node.date)}
                  </Typography>
                  {node.description && (
                    <Typography variant="caption" color="text.secondary" noWrap>
                      {node.description}
                    </Typography>
                  )}
                </>
              }
            />
          </ListItem>
        ))}
        {nodes.length === 0 && (
          <Box sx={{ p: 2, textAlign: 'center' }}>
            <Typography variant="body2" color="text.secondary">
              暂无时间节点，点击右上角添加
            </Typography>
          </Box>
        )}
      </List>

      <Dialog open={dialogOpen} onClose={handleCloseDialog} maxWidth="sm" fullWidth>
        <DialogTitle>{editMode ? '编辑时间节点' : '添加时间节点'}</DialogTitle>
        <DialogContent>
          <TextField
            autoFocus
            label="标题"
            fullWidth
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            sx={{ mt: 2, mb: 2 }}
          />
          <TextField
            label="日期"
            type="date"
            fullWidth
            value={date}
            onChange={(e) => setDate(e.target.value)}
            InputLabelProps={{ shrink: true }}
            sx={{ mb: 2 }}
          />
          <TextField
            label="描述"
            fullWidth
            multiline
            rows={4}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseDialog}>取消</Button>
          <Button onClick={handleSubmit} variant="contained" disabled={!title.trim()}>
            {editMode ? '保存' : '创建'}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
